name: Monorepo
on:
  push:
    branches:
      - master
    path:
      - 'monorepo/**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloudAdmin:
    name: SonarCloud Admin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install dependencies
        run: yarn
      - name: SonarCloud Admin
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ github.workspace }}/packages/admin
          args: >
            -Dsonar.organization=mesmerize86
            -Dsonar.projectKey=mesmerize86_admin
  sonarcloudEcomm:
    name: SonarCloud Ecomm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: action/checkout@v3
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.13.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ${{ github.workspace }}/packages/ecomm
      - name: Install dependencies
        run: pnpm install
      - name: Linting
        run: pnpm lint
      - name: Unit Test
        run: pnpm test
      - name: SonarCloud Ecom
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ github.workspace }}/packages/ecomm
          args: >
            -Dsonar.organization=mesmerize86
            -Dsonar.projectKey=mesmerize86_ecomm