name: Ecomm SonarCloud
on:
  push:
    paths:
      - 'packages/ecomm/**'
      - '.github/workflows/**'
    branches:
      - master
  pull_request:
    paths:
        - 'packages/ecomm/**'
        - '.github/workflows/**'
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  checks:   write
jobs:
  sonarcloudScan1:
    name: SonarCloudScan1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Dependencies
        working-directory: packages/ecomm
        run: yarn install

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

#      - name: Run linters
#        working-directory: packages/ecomm
#        run:  yarn add -g eslint

#      - name: Run linters
#        uses: wearerequired/lint-action@v2
#        with:
#          eslint: true
#          eslint_dir: packages/ecomm
#          prettier: true
#          prettier_dir: packages/ecomm


      - run: echo ${{ github.workspace }}
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          working-directory: ${{ github.workspace }}/packages/ecomm
          package-manager: yarn
          test-script: yarn coverage
          skip-step: all
          output: report-markdown
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}

#      - name: Test
#        working-directory: packages/ecomm
#        run: yarn run coverage

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          projectBaseDir: packages/ecomm
      

#  sonarcloudScan2:
#    name: SonarCloudScan2
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          projectBaseDir: packages/admin
